#!/usr/bin/env bash

# Only run if $HOME is set
if [ -z "$HOME" ]; then echo "\$HOME not set"; exit 1; fi

# ZSH Setup
#
echo "Installing Oh-My-ZSH..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Download and install Homebrew
#
echo "Installing Homebrew..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap caskroom/cask
brew update

# Installing apps
echo "Installing apps..."
brew cask install sublime-text
brew cask install iterm2
brew cask install moom
brew cask install sequel-pro

# Installing tools
echo "Installing tools..."
brew install php
brew install composer
brew install node
brew install yarn

composer global require "consolidation/cgr"
$HOME/.composer/vendor/bin/cgr "laravel/installer"
$HOME/.composer/vendor/bin/cgr "laravel/valet"
$HOME/.composer/vendor/bin/valet install
$HOME/.composer/vendor/bin/valet park $HOME/Sites

echo "Setting up dotfiles..."

DOTFILES=$HOME/.dotfiles
echo "Cloning repository to ~/.dotfiles..."
rm -rf $DOTFILES
/usr/bin/git clone --depth=1 https://github.com/GeorgThomassen/dotfiles.git $DOTFILES
/usr/bin/git --git-dir $DOTFILES/.git remote rm origin
/usr/bin/git --git-dir $DOTFILES/.git remote add origin git@github.com:GeorgThomassen/dotfiles.git
rm -rf $HOME/.zshrc $HOME/.gitignore $HOME/.gitconfig

ln -s $DOTFILES/zshrc $HOME/.zshrc
ln -s $DOTFILES/gitconfig $HOME/.gitconfig
ln -s $DOTFILES/gitignore $HOME/.gitignore
ln -s $DOTFILES/*.zsh-theme ~/.oh-my-zsh/themes
mkdir $HOME/Sites

echo "Setting up SSH"
echo "What's your email?"
read EMAIL

# Setting up SSH
#
echo "Generating SSH keys for "$EMAIL"..."
ssh-keygen -t rsa -b 4096 -C $EMAIL -f $HOME/.ssh/id_rsa
echo "Starting SSH-agent..."
eval "$(ssh-agent -s)"

cat <<EOM >$HOME/.ssh/config
Host *
 AddKeysToAgent yes
 UseKeychain yes
 IdentityFile ~/.ssh/id_rsa
EOM

ssh-add -K $HOME/.ssh/id_rsa
pbcopy < $HOME/.ssh/id_rsa.pub
echo "The public key has been copied to the clipboard"
echo "Go to https://github.com/settings/keys to add it"
echo
echo "Done setting up dotfiles..."
exit 0;